#cloud-config

# Benutzerkonfiguration
users:
  - name: ubuntu               # Name des Benutzers
    sudo: ALL=(ALL) NOPASSWD:ALL  # Der Benutzer hat sudo-Rechte ohne Passwortabfrage
    groups: users, admin       # Der Benutzer gehört zu den Gruppen 'users' und 'admin'
    home: /home/ubuntu         # Heimatverzeichnis des Benutzers
    shell: /bin/bash           # Standard-Shell des Benutzers
    ssh_authorized_keys:       # Autorisierte SSH-Schlüssel für den Benutzer
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCLIezEweG9sEM9nFZS6grKOLs1hNNjGCjX8o4M196vQbkQwH4SEa1vn9hfR7nK/nM7spaczYPyXdLcrMb+7Bd3JYg1O5U4euEgS94WIdO2s4kOirtqu2HuvI0wiR19jWoyUFwmtNObhomDSb6spWYyEcGWpCZN9opJWZiFIATWbBP65TfwKuJO8i3uHSqYC0GWcW7eSn656F6D3mgXoyx4+otDcRJOWQKfhGqUZyJM68wZKbHnvjI50J3ZnkW6Gu6Fn77IdX8U4CS0//XjYYBONhtRoY6LRz98covesT5mkGKKnT9Ci200M21fklsh/X8bKjudYZXJKa+NK0ariZBt aws-key # Mein public Key

# Öffentlicher Schlüssel der Lehrperson (Nussle)
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC0WGP1EZykEtv5YGC9nMiPFW3U3DmZNzKFO5nEu6uozEHh4jLZzPNHSrfFTuQ2GnRDSt+XbOtTLdcj26+iPNiFoFha42aCIzYjt6V8Z+SQ9pzF4jPPzxwXfDdkEWylgoNnZ+4MG1lNFqa8aO7F62tX0Yj5khjC0Bs7Mb2cHLx1XZaxJV6qSaulDuBbLYe8QUZXkMc7wmob3PM0kflfolR3LE7LResIHWa4j4FL6r5cQmFlDU2BDPpKMFMGUfRSFiUtaWBNXFOWHQBC2+uKmuMPYP4vJC9sBgqMvPN/X2KyemqdMvdKXnCfrzadHuSSJYEzD64Cve5Zl9yVvY4AqyBD aws-key

# Passwortauthentifizierung über SSH deaktivieren
ssh_pwauth: false

# Root-Zugriff nicht deaktivieren
disable_root: false 

# Systempakete aktualisieren
package_update: true

# Liste der zu installierenden Pakete
packages:
  - curl    # Tool zum Abrufen von Dateien über verschiedene Protokolle
  - wget    # Tool zum Herunterladen von Dateien aus dem Internet
  - apache2
  - php
  - libapache2-mod-php
  - mariadb-server
  - php-mysqli

runcmd:
  - sudo apt update
  
  - sudo apt install -y apache2
  - sudo apt install -y php
  - sudo apt install -y libapache2-mod-php
  
  - sudo apt install -y mariadb-server
  
  - sudo apt install -y php-mysqli
  
  - sudo mysql -sfu root -e "GRANT ALL ON *.* TO 'admin'@'%' IDENTIFIED BY 'password' WITH GRANT OPTION;"
  
  - sudo systemctl restart mariadb.service
  
  - sudo systemctl restart apache2
  
  - cd /home/ubuntu
  
  - git clone https://gitlab.com/ch-tbz-it/Stud/m346/m346scripts.git .
  
  - sudo cp ./m346scripts/KN01/*.php /var/www/html/
