#cloud-config
users:
  - name: ubuntu
    sudo: ALL=(ALL) NOPASSWD:ALL
    groups: users, admin
    home: /home/ubuntu
    shell: /bin/bash
    ssh_authorized_keys:
     #Key lehrer nussle
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC0WGP1EZykEtv5YGC9nMiPFW3U3DmZNzKFO5nEu6uozEHh4jLZzPNHSrfFTuQ2GnRDSt+XbOtTLdcj26+iPNiFoFha42aCIzYjt6V8Z+SQ9pzF4jPPzxwXfDdkEWylgoNnZ+4MG1lNFqa8aO7F62tX0Yj5khjC0Bs7Mb2cHLx1XZaxJV6qSaulDuBbLYe8QUZXkMc7wmob3PM0kflfolR3LE7LResIHWa4j4FL6r5cQmFlDU2BDPpKMFMGUfRSFiUtaWBNXFOWHQBC2+uKmuMPYP4vJC9sBgqMvPN/X2KyemqdMvdKXnCfrzadHuSSJYEzD64Cve5Zl9yVvY4AqyBD aws-key
    #Key leona
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCLIezEweG9sEM9nFZS6grKOLs1hNNjGCjX8o4M196vQbkQwH4SEa1vn9hfR7nK/nM7spaczYPyXdLcrMb+7Bd3JYg1O5U4euEgS94WIdO2s4kOirtqu2HuvI0wiR19jWoyUFwmtNObhomDSb6spWYyEcGWpCZN9opJWZiFIATWbBP65TfwKuJO8i3uHSqYC0GWcW7eSn656F6D3mgXoyx4+otDcRJOWQKfhGqUZyJM68wZKbHnvjI50J3ZnkW6Gu6Fn77IdX8U4CS0//XjYYBONhtRoY6LRz98covesT5mkGKKnT9Ci200M21fklsh/X8bKjudYZXJKa+NK0ariZBt aws-key
ssh_pwauth: false
disable_root: false
package_update: true
packages:
  - curl
  - wget
  - mariadb-server
runcmd:
  - sudo mysql -sfu root -e "GRANT ALL ON *.* TO 'admin'@'%' IDENTIFIED BY 'password' WITH GRANT OPTION;"
  - sudo sed -i 's/127.0.0.1/0.0.0.0/g' /etc/mysql/mariadb.conf.d/50-server.cnf
  - sudo systemctl restart mariadb.service
